### ISSUE TITLE
Foundationカスタムテーマの作成

### ISSUE THREAD

**Issue by rayfields** [interestic/oscillo#10]
Oscilloオリジナリティを持たせるためにカスタムします。
極力すべてのコンポーネントに対応できたらいいな。

**Comment by rayfields** [comment]
本体で開発するのではなく、外部モジュールとして開発しようかと考えている。
んで、それをBowerからインストールして使用する。

そうしておけば、WEBアプリ以外の関連プロダクト（もしできれば）でも使えるし、統一感がでると思う。

**Comment by rayfields** [comment]
とりあえず、レポジトリだけ作った
https://github.com/interestic/kingsroad

**Comment by do9iigane** [comment]
ドキがムネムネします。

**Comment by rayfields** [comment]
ぼくも作る前からわくわくです 😆

**Comment by rayfields** [comment]
こちらのIssueで管理するので、クローズします。
https://github.com/interestic/kingsroad
